### ISSUE TITLE
NVD now use JSON 1.1 Vulnerability Feed

### ISSUE THREAD

**Issue by Capashenn** [olbat/nvdcve#1]
Could you update your script update and fetch to use the last JSON 1.1.
https://nvd.nist.gov/General/News/JSON-1-1-Vulnerability-Feed-Release

the new URL is : https://nvd.nist.gov/feeds/json/cve/1.1
and files are : 	
meta_file_url="${CVE_BASE_URL}/nvdcve-1.1-${1}.meta"
json_file_url="${CVE_BASE_URL}/nvdcve-1.1-${1}.json.gz"

Thanks.

**Comment by olbat** [comment]
Of course. Thank you for notifying me about the new version 👍
