### ISSUE TITLE
Updates have stopped?

### ISSUE THREAD

**Issue by PandaWill** [olbat/nvdcve#4]
Is it possible for you to fix the automatic updates to this please?

I have tried using CVEProject/cvelist but they are missing all the CVSSv2 info.

Many thanks

**Comment by olbat** [comment]
Hey, I'm sorry, TravisCI has changed it's free subscription model and automated updates of this project are powered by it. I ran out of credit. I'll try to check if I can move the CI to GitLab.org to fix the problem.

**Comment by olbat** [comment]
I just fixed the issue by changing CI to use GitLab. Small bonus, the repository is now updated on an hourly basis :)
